---
version: "3.8"
services:
  movies:
    image: saibootla/paytmmoviesrepo:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
  train:
    image: saibootla/paytmtrainrepo:latest
    ports:
      - 82:80
    deploy:
      replicas: 3
  recharge:
    image: saibootla/paytmrechargerepo:latest
    ports:
      - 83:80
    deploy:
      replicas: 3
  dth:
    image: saibootla/paytmdthrepo:latest
    ports:
      - 84:80
    deploy:
      replicas: 3
